name: EMS-ESP CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

on:
  pull_request:

jobs:
  emsesp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        # platformio upgrade --dev
        platformio upgrade
        platformio update
    - name: Run PlatformIO
      run: | 
        platformio run

            
      
